name: bios8366_win

channels:
 - conda-forge
 - anaconda
 
dependencies:
- python=3.6
- autograd
- basemap
- bokeh
- cython
- dask
- ipython
- jupyter
- jupyterlab
- notebook
- ipyparallel
- ipywidgets
- jupyter_client
- jupyter_core
- line_profiler
- numexpr
- numba
- numpy
- pandas
- patsy
- pillow
- pip
- pprofile
- python-graphviz
- rpy2  
- scikit-learn
- scipy
- seaborn
- snakeviz
- sympy
- theano
- xlrd
- pymc3